name: 回帖

on:
  push:
   branches: main
   paths: 
     - 'README.md'
  schedule:
    - cron: '5 14 * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements #安装模块
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: start
      run: |
        python src/main.py
    - name: Commit
      run: |
        git config --global user.email actionbot@email.com
        git config --global user.name actionbot
        git add .
        git commit -m "更新输出日志" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
